Hello Microverse Project: Add homepage
Graycemuthui/Hello-Microverse pull request #1
Opened 2022-04-19 21:37 UTC by Graycemuthui

- Created a repository on GitHub.
-  Added linter configurations.
- Created .gitignore file and added test.md file.
- Created HTML file with a heading.
- Created a CSS file and added style to the heading.
- Used proper GitHub flow.
- Followed all project and general guidelines.

Kindly review and provide feedback.
Thanks.

2022-04-19 22:44 UTC, mahbubul14 requested changes
Hi @Graycemuthui ,

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

# Required Changes ♻️

- [ ] The `README` file should be descriptive. Please check [this template ](https://github.com/microverseinc/readme-template) and update your `README` file.

###  To Highlights
:heavy_check_mark: No linters error.
:heavy_check_mark: Correct github-flow.
:heavy_check_mark: Descriptive PR title & description.

### Optional suggestions

- [ ] Check the comments under the review for more suggestions. :arrow_down: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-04-19 22:44 UTC, mahbubul14 commented on index.html
> +</body>
- [ ] For readability, please add two spaces of indentation. We should not use the tab key. You can check [HTML & CSS best practices. ](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md)

2022-04-20 00:00 UTC, roshan-bajgain approved these changes
# Approved 👏 

Hi @Graycemuthui , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

To Highlight: 
- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error at present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashboard. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2022-04-20 00:08 UTC, merged

2022-04-20 00:20 UTC, Graycemuthui commented
@mahbubul14 and @roshan-bajgain 
Thank you so much for the reviews.